#!/usr/bin/bash
# @brief Configure cmake for DKRZ Levante 
cmake -S . -B build \
    -DCMAKE_Fortran_COMPILER=mpiifort \
    -DMKLLIB=/sw/intel/oneapi/mkl/2021.3.0/lib/intel64\
    -DMKLINCLUDE=/sw/intel/oneapi/mkl/2021.3.0/include
