#!/usr/bin/bash
# @brief Configure cmake for DKRZ Levante 
curdir=$(pwd)
[[ $curdir == *"config"* ]] && echo "must be in root project dir" && exit 1 
cmake -S . -B build \
    -DCMAKE_Fortran_COMPILER=mpiifort \
    -DCMAKE_PREFIX_PATH=$(pwd)/build/extern/pFUnit \
    -DMKLLIB=/sw/intel/oneapi/mkl/2021.3.0/lib/intel64\
    -DMKLINCLUDE=/sw/intel/oneapi/mkl/2021.3.0/include
