#!/usr/bin/bash
# @brief Baseline configuration assuming standard oneapi installation via apt.
(
curdir=$(pwd)
[[ $curdir == *"config"* ]] && echo "must be in root project dir" && exit 1 
cmake -S . -B build\
    -DBUILD_TESTING=ON\
    -DENABLE_PFUNIT=ON\
    -DENABLE_SPBLAS=ON\
    -DENABLE_TEST_DRIVE=OFF\
    -DCMAKE_Fortran_COMPILER=mpiifx\
    -DCMAKE_INSTALL_PREFIX=build/installed
cmake --build build
cd build
ctest -L testlib 
./build/test/test_spblas
)
