#!/usr/bin/bash
# @brief Baseline configuration assuming standard oneapi installation via apt.
builddocs=$1
DEFAULT_FIND_INTEL_MKL="ON"
FIND_INTEL_MKL="${FIND_INTEL_MKL:-$DEFAULT_FIND_INTEL_MKL}"
curdir=$(pwd)
[[ $curdir == *"config"* ]] && echo "must be in root project dir" && exit 1 
#[[ -d build ]] && rm -rf build
cmake -S . -B build\
    -DCMAKE_BUILD_PARALLEL_LEVEL=8\
    -DCMAKE_Fortran_COMPILER=ifx\
    -DBUILD_TESTING=ON\
    -DENABLE_TEST_DRIVE=ON\
    -DENABLE_FFTPACK=ON\
    -DENABLE_SPBLAS=ON\
    -DENABLE_FIND_INTEL_MKL=${FIND_INTEL_MKL}\
    -DENABLE_PFUNIT=OFF\
    -DCMAKE_INSTALL_PREFIX=build/installed
cmake --build build
cmake --build build --target install
cmake --build build --target testlib
[[ -n $builddocs ]] && cmake --build build --target doxygen_docs 

