#!/usr/bin/bash
# @brief Configure cmake for DKRZ Levante 
(
curdir=$(pwd)
[[ $curdir == *"config"* ]] && echo "must be in root project dir" && exit 1 
cmake -S . -B build \
    -DCMAKE_Fortran_COMPILER=mpiifort \
    -DMKLLIB=/sw/spack-levante/intel-oneapi-mkl-2022.0.1-ttdktf/mkl/2022.0.1/lib/intel64/\
    -DMKLINCLUDE=/sw/spack-levante/intel-oneapi-mkl-2022.0.1-ttdktf/mkl/latest/include/\
    -DCMAKE_INSTALL_PREFIX=build/installed\
    -DPFUNIT=ON
    
cmake --build build
cd build
ctest -L myproject 
)
